export const lecturerAdminCodes = ["ANS", "MCT", "MCU"];

export const lecturers: {
  code: string;
  nip: string;
  name: string;
  email: string;
  kk: string[];
}[] = [
  {
    code: "AAF",
    nip: "199104162019031015",
    name: "Aidil Afriansyah, S.Kom., M.Kom",
    email: "aidil.afriansyah@if.itera.ac.id",
    kk: ["PPMP", "HCIU", "WEBI", "MOBL"],
  },
  {
    code: "AIQ",
    nip: "199108022019031013",
    name: "Amirul Iqbal, S.Kom., M.Eng",
    email: "amirul.iqbal@if.itera.ac.id",
    kk: ["DSKT", "PPMP", "LITR", "MLTR"],
  },
  {
    code: "ANS",
    nip: "199111272022031007",
    name: "Andika Setiawan, S.Kom., M.Cs.",
    email: "andika.setiawan@if.itera.ac.id",
    kk: ["MLTR", "DLCV", "IMAG", "WEBI"],
  },
  {
    code: "AFO",
    nip: "198602142019031008",
    name: "Andre Febrianto, S.Kom., M.Eng",
    email: "andre.febrianto@if.itera.ac.id",
    kk: ["WEBI", "DSKT", "HCIU", "PPMP"],
  },
  {
    code: "AWJ",
    nip: "19920508201801098",
    name: "Angga Wijaya, S.Si., M.Si.",
    email: "angga.wijaya@if.itera.ac.id",
    kk: ["KRIP", "ALGO", "MLTR", "CYBR"],
  },
  {
    code: "AIC",
    nip: "199008112019031011",
    name: "Arief Ichwani, S.Kom., M.Cs",
    email: "arief.ichwani@if.itera.ac.id",
    kk: ["WEBI", "WEBI", "MLTR", "DLCV"],
  },
  {
    code: "AZR",
    nip: "199004042019031020",
    name: "Arkham Zahri Rakhman, S.Kom., M.Eng.",
    email: "arkham@if.itera.ac.id",
    kk: ["DATA", "ALGO", "IOTC", "MOBL"],
  },
  {
    code: "EDN",
    nip: "19910209202406001",
    name: "Eko Dwi Nugroho, S.Kom., M.Cs.",
    email: "eko.nugroho@if.itera.ac.id",
    kk: ["ALGO", "WEBI", "IOTC", "MLTR"],
  },
  {
    code: "HBF",
    nip: "199108242019031014",
    name: "Hafiz Budi Firmansyah, Ph.D.",
    email: "hafiz.budi@if.itera.ac.id",
    kk: ["MLTR", "DLCV", "PPMP", "HCIU"],
  },
  {
    code: "HTA",
    nip: "199205222019031012",
    name: "Hartanto Tantriawan, S.Kom., M.Kom",
    email: "hartanto.tantriawan@if.itera.ac.id",
    kk: ["NETW", "DATA", "CYBR", "DLCV"],
  },
  {
    code: "IWW",
    nip: "198903222019031009",
    name: "I Wayan Wiprayoga Wisesa, S.Kom., M.Kom.",
    email: "wayan.wisesa@if.itera.ac.id",
    kk: ["MMED", "DLCV", "MLTR", "SIGN"],
  },
  {
    code: "IFA",
    nip: "199303142019031018",
    name: "Ilham Firman Ashari, S.Kom., M.T",
    email: "firman.ashari@if.itera.ac.id",
    kk: ["CYBR", "WEBI", "IOTC", "KRIP"],
  },
  {
    code: "IEW",
    nip: "198905172019031013",
    name: "Imam Eko Wicaksono, S.Si., M.Si.",
    email: "imam.wicaksono@if.itera.ac.id",
    kk: ["DLCV", "ALGO", "MLTR", "DLNL"],
  },
  {
    code: "LIA",
    nip: "1997081720242294",
    name: "Leslie Anggraini, S.Kom., M.Kom.",
    email: "leslie.anggraini@if.itera.ac.id",
    kk: ["MLTR", "VISD", "DLCV", "ALGO"],
  },
  {
    code: "MHA",
    nip: "199105252022031002",
    name: "M Habib Algifari, S.Kom., M.T.I.",
    email: "muhammad.algifari@if.itera.ac.id",
    kk: ["WEBI", "MOBL", "IOTC", "IMAG"],
  },
  {
    code: "MCT",
    nip: "199301092019031017",
    name: "Martin Clinton Tosima Manullang, Ph.D.",
    email: "martin.manullang@if.itera.ac.id",
    kk: ["MLTR", "DLCV", "MMED", "TEXT"],
  },
  {
    code: "MCU",
    nip: "198905182019031011",
    name: "Meida Cahyo Untoro, S.Kom., M.Kom",
    email: "cahyo.untoro@if.itera.ac.id",
    kk: ["DATA", "MLTR", "WEBI", "DATA"],
  },
  {
    code: "MIV",
    nip: "199209052022032008",
    name: "Miranti Verdiana, M.Si",
    email: "miranti.verdiana@if.itera.ac.id",
    kk: ["MLTR", "WEBI", "DLCV", "ALGO"],
  },
  {
    code: "MIR",
    nip: "198610102019031016",
    name: "Mohamad Idris, S.Si., M.Sc.",
    email: "mohamad.idris@if.itera.ac.id",
    kk: ["IMAG", "KRIP", "HCIU", "MLTR"],
  },
  {
    code: "MPS",
    nip: "198509212019031012",
    name: "Mugi Praseptiawan, S.T., M.Kom",
    email: "mugi.praseptiawan@if.itera.ac.id",
    kk: [],
  },
  {
    code: "RDB",
    nip: "199411272020121018",
    name: "Radhinka Bagaskara, S.Si.Kom., M.Si., M.Sc.",
    email: "radhinka.bagaskara@if.itera.ac.id",
    kk: ["GAME", "VISD", "MLTR", "ALGO"],
  },
  {
    code: "RIK",
    nip: "199105302019031018",
    name: "Rahman Indra Kesuma, S.Kom. M.Cs.",
    email: "rahman.indra@if.itera.ac.id",
    kk: ["DLCV", "DLNL", "MLTR", "DATA"],
  },
  {
    code: "RHA",
    nip: "198904152015042006",
    name: "Raidah Hanifah, S.T., M.T.",
    email: "raidah.hanifah@if.itera.ac.id",
    kk: [],
  },
  {
    code: "RAY",
    nip: "198803092015041002",
    name: "Rajif Agung Yunmar, S.Kom., M.Cs.",
    email: "rajif@if.itera.ac.id",
    kk: ["CYBR", "NETW", "WEBI", "MOBL"],
  },
  {
    code: "WIY",
    nip: "199307272022032022",
    name: "Winda Yulita, S.Pd., M.Cs.",
    email: "winda.yulita@if.itera.ac.id",
    kk: ["TEXT", "DLNL", "MLTR", "WEBI"],
  },
  {
    code: "WON",
    nip: "195910141985031003",
    name: "Prof. Sarwono Sutikno",
    email: "sarwono.sutikno@if.itera.ac.id",
    kk: ["CYBR", "IOTC", "KRIP", "ROBO"],
  },
  {
    code: "HLS",
    nip: "HLS",
    name: "Ir. Hira Laksmiwati Soemitro, M.Sc.",
    email: "hira@informatika.org",
    kk: ["WEBI", "DATA", "HCIU", "VISD"],
  },
  {
    code: "ALY",
    nip: "ALY",
    name: "Alya Khairunnisa Rizkita, S.Kom., M.Kom.",
    email: "alya.rizkita@if.itera.ac.id",
    kk: [],
  },
];

export const expertiseList = [
  { name: "MLTR", description: "Traditional Machine Learning (All Domain)" },
  { name: "DLCV", description: "Deep Learning – Citra" },
  { name: "DLNL", description: "Deep Learning – NLP" },
  { name: "CYBR", description: "Keamanan Siber" },
  { name: "NETW", description: "Jaringan Komputer" },
  {
    name: "IOTC",
    description: "Internet of Things & Embedded System & Cloud Computing",
  },
  { name: "MOBL", description: "Pengembangan Perangkat Lunak – Mobile" },
  {
    name: "WEBI",
    description: "Pengembangan Perangkat Lunak – Web & Sistem Informasi",
  },
  { name: "DSKT", description: "Pengembangan Perangkat Lunak – Desktop" },
  {
    name: "PPMP",
    description: "Pengembangan Perangkat Lunak – Multi Platform",
  },
  { name: "DATA", description: "Basis Data & Data Mining & Data Warehouse" },
  { name: "LITR", description: "Riset Literatur" },
  { name: "GAME", description: "Game" },
  { name: "VRAR", description: "Virtual Reality / Augmented Reality" },
  { name: "ROBO", description: "Robotika / Kontrol Kendali Cerdas" },
  { name: "ALGO", description: "Strategi dan Algoritma" },
  { name: "MMED", description: "Multimedia" },
  { name: "COMP", description: "Teknologi Kompresi" },
  { name: "HCIU", description: "Interaksi Manusia dan Komputer, UI, UX" },
  { name: "SIGN", description: "Pengolahan Sinyal" },
  { name: "IMAG", description: "Pengolahan Citra" },
  { name: "TEXT", description: "Pemrosesan Teks" },
  { name: "VISD", description: "Visualisasi Data" },
  { name: "KRIP", description: "Kriptografi" },
];
